---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-techical-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-techical-test-app
  template:
    metadata:
      labels:
        app: ts-techical-test-app
    spec:
      containers:
      - name: ts-techical-test-app
        image: ts-techical-test-app:latest
        imagePullPolicy: IfNotPresent  # Use the locally available image
        ports:
        - containerPort: 3000
